name: Kind
on: [pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      env:
        KIND_BDD_SECRETS: ${{ secrets.KIND_BDD_SECRETS }}
        GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      run: |
        sudo jx/bdd/kind/ci.sh