name: Kind
on: [pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      env:
        KIND_BDD_SECRETS: ${{ secrets.KIND_BDD_SECRETS }}
        GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
      run: |
        export KIND_VERSION=0.8.1
        export JX_VERSION=0.0.286

        mkdir $HOME/bin
        export PATH=$PATH:$HOME/bin

        # use a sub dir for downloading to avoid clashing with the jx dir etc
        mkdir downloads
        cd downloads

        curl -L https://github.com/jenkins-x/jx-cli/releases/download/v${JX_VERSION}/jx-cli-linux-amd64.tar.gz | tar xzv
        sudo mv jx /usr/local/bin

        curl -L https://github.com/kubernetes-sigs/kind/releases/download/v${KIND_VERSION}/kind-linux-amd64
        chmod +x kind-linux-amd64
        sudo mv kind-linux-amd64 /usr/local/bin/kind

        cd ..

        echo "now testing the binary:"
        jx help

        # BDD test specific part
        export BDD_NAME="bdd-gke"

        # the gitops repository template to use
        export GITOPS_TEMPLATE_PROJECT="jx3-gitops-repositories/jx3-kind-vault"

        jx/bdd/ci.sh