name: Kind
on:
  pull_request:
    types:
      - labeled
jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      if: github.repository_owner == 'jenkins-x' && github.event.label.name == 'testkind'
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
      run: |

        if [ -z "$GH_ACCESS_TOKEN" ]
        then
              echo "ERROR: no GH_ACCESS_TOKEN env var defined for kind.yaml"
        else
              echo "has valid git token for kind.yaml"
        fi

        sudo -E ./jx/bdd/kind/ci.sh
