name: Kind
on: [pull_request]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Kind
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
      run: |
        sudo -E ./jx/bdd/kind/ci.sh
